name: main

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: flake8 .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # - uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t tulsu_devops-case1:${{ github.sha }} .

    - name: Smoke test container
      run: |
        docker run -d -p 6996:6996 --name test tulsu_devops-case1:${{ github.sha }}
        for i in {1..10}; do
          curl -s http://localhost:6996 && exit 0 || sleep 2
        done
        echo "Container did not respond!" && docker logs test && exit 1

    - name: Cleanup
      if: always()
      run: docker rm -f test || true